### ISSUE TITLE
How to use ansible-opendaylight in Ubuntu environment?

### ISSUE THREAD

**Issue by Shelphy** [dfarrell07/ansible-opendaylight#24]
Hi Daniel, I am from OPNFV compass team. We are going to use this ansible-opendaylight in our compass installer which supports both centos and ubuntu os. It seems that currently only rpm package of ODL release is supported. So, will you also support deb package of ODL release?

**Comment by dfarrell07** [comment]
Hello @Shelphy, thanks for asking. Yes, I talked with Compass folks about this at OPNFV Summit. As promised, I've been mentoring a Linux Foundation intern to add .deb build logic to ODL upstream. That project is done and the [logic is here](https://github.com/opendaylight/integration-packaging/tree/master/deb). Akshita is technically done with her internship, but I'm hoping she's willing to continue contributing by getting these debs hosted for downstream consumption. I'll send her this tread via email now.

**Comment by Shelphy** [comment]
Glad to hear that. Thanks a lot!

**Comment by AkshitaJha** [comment]
Hi @Shelphy ,
Deb support has now been added to ansible-opendaylight. It has been tested for Ubuntu 16.04 and Debian 8. Please let me know in case you face any issue.
Thanks.

**Comment by Shelphy** [comment]
Hi @AkshitaJha 
Really awesome! I'll try it later. Thanks!

**Comment by dfarrell07** [comment]
> I'll try it later.
@Shelphy 

You can test it pretty easily via @AkshitaJha's [Vagrant base box examples of Ansible/Deb-based ODL deployments](https://github.com/dfarrell07/vagrant-opendaylight/pull/31/files).
